pr: none
trigger:
- main

pool: Default

stages:
- stage: Test
  dependsOn: [] # Run in parallel
  jobs:
  - job: E2ETest
    steps:
    - script: |
        source ./.pipeliner/init
        Pipeliner_Test_Run e2e
      displayName: Run E2E tests

    - publish: $(Build.ArtifactStagingDirectory)/testReports
      artifact: E2ETestReport
      displayName: Publish test report
      condition: always()

- stage: Build
  dependsOn: [] # Run in parallel
  jobs:
  - job: CreatePackage
    steps:
    - script: |
        source ./.pipeliner/init
        Pipeliner_Package_Create

        package=$(Variables_Get "package")
        Variables_Set "packageName" "$(basename "$package")"
      displayName: Create package

    - publish: $(Build.ArtifactStagingDirectory)/packages
      artifact: Packages
      displayName: Publish package