pr:
- main
trigger: none

pool: Default

stages:
- stage: Test
  jobs:
  - job: UnitTest
    steps:
    - bash: |
        source ./.pipeliner/init
        Pipeliner_Test_Run unit
      displayName: Run Unit tests

    - publish: $(Build.ArtifactStagingDirectory)/testReports
      artifact: UnitTestReport
      displayName: Publish test report
      condition: always()


  - job: IntegrationTest
    steps:
    - script: |
        source ./.pipeliner/init
        Pipeliner_Test_Run integration
      displayName: Run Integration tests

    - publish: $(Build.ArtifactStagingDirectory)/testReports
      artifact: IntegrationTestReport
      displayName: Publish test report
      condition: always()