pr:
- main

pool: Default

stages:
- stage: Test
  jobs:
  - job: UnitTest
    steps:
    - bash: |
        source ./.pipeliner/init.sh
        Pipeliner_Test_Run unit
      displayName: Run unit tests

    - download: current
      artifact: Test Reports
      displayName: Download test reports
      condition: always()
    - publish: $(Build.ArtifactStagingDirectory)/testReports
      artifact: Test Reports
      displayName: Publish test reports
      condition: always()


  - job: IntegrationTest
    steps:
    - script: |
        source ./.pipeliner/init.sh
        Pipeliner_Test_Run integration
      displayName: Run integration tests

    - download: current
      artifact: Test Reports
      displayName: Download test reports
      condition: always()
    - publish: $(Build.ArtifactStagingDirectory)/testReports
      artifact: Test Reports
      displayName: Publish test reports
      condition: always()


  - job: E2ETest
    steps:
    - script: |
        source ./.pipeliner/init.sh
        Pipeliner_Test_Run e2e
      displayName: Run E2E tests

    - download: current
      artifact: Test Reports
      displayName: Download test reports
      condition: always()
    - publish: $(Build.ArtifactStagingDirectory)/testReports
      artifact: Test Reports
      displayName: Publish test reports
      condition: always()
