pr:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: UnitTest
  steps:
  - bash: |
      source ./.pipeliner/init.sh
      Pipeliner_Test_Run unit
    displayName: Run unit tests

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)/testReports
      artifact: testReports
    condition: always()


- job: IntegrationTest
  steps:
  - script: |
      source ./.pipeliner/init.sh
      Pipeliner_Test_Run integration
    displayName: Run integration tests

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)/testReports
      artifact: testReports
    condition: always()


- job: E2ETest
  steps:
  - script: |
      source ./.pipeliner/init.sh
      Pipeliner_Test_Run e2e
    displayName: Run E2E tests


  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)/testReports
      artifact: testReports
    condition: always()