name: Pipeliner CI

on:
  pull_request:
    branches:
      - main

jobs:
  Unit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Run unit tests
      run: |
        source ./.pipeliner/init.sh
        Pipeliner_Test_Run unit

  Integration_test:
    runs-on: ubuntu-latest
    steps:
    - name: Run integration tests
      run: |
        source ./.pipeliner/init.sh
        Pipeliner_Test_Run integration

  E2E_test:
    runs-on: ubuntu-latest
    steps:
    - name: Run E2E tests
      run: |
        source ./.pipeliner/init.sh
        Pipeliner_Test_Run e2e