name: Pipeliner CI

on:
  workflow_dispatch: #Allow manual run
  pull_request:
    branches:
      - main

jobs:
  Unit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Unit tests
      run: |
        source ./.pipeliner/init
        Pipeliner_Test_Run unit

    - name: Publish test report
      uses: actions/upload-artifact@v4
      with:
        name: UnitTestReport
        path: artifacts/testReports/
      if: always()


  Integration_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Integration tests
      run: |
        source ./.pipeliner/init
        Pipeliner_Test_Run integration

    - name: Publish test report
      uses: actions/upload-artifact@v4
      with:
        name: IntegrationTestReport
        path: artifacts/testReports/
      if: always()