name: Pipeliner CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run unit tests
      run: |
        source ./.pipeliner/init.sh
        Pipeliner_Test_Run unit

    - name: Run integration tests
      run: |
        source ./.pipeliner/init.sh
        Pipeliner_Test_Run integration
