name: Pipeliner CI

on:
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run unit tests
      run: |
        source ./.pipeliner/init.sh
        Pipeliner_Test_Run unit
      if: always()

    - name: Run integration tests
      run: |
        source ./.pipeliner/init.sh
        Pipeliner_Test_Run integration
      if: always()

    - name: Run E2E tests
      run: |
        source ./.pipeliner/init.sh
        Pipeliner_Test_Run e2e
      if: always()

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: testReports
        path: artifacts/testReports/
      if: always()